// /**
//  * @author: Nguyen Van Viet
//  * @email: vietqb9779@gmail.com
//  */
// //login
// const REQUEST_LOGIN = 'REQUEST_LOGIN';
// const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
// const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';
// // Input
// const EMAIL_CHANGED = 'EMAIL_CHANGED';
// const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
// //log out
// const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
// const REQUEST_LOGOUT_SUCCESS = 'REQUEST_LOGOUT_SUCCESS';
// const REQUEST_LOGOUT_FAILED = 'REQUEST_LOGOUT_FAILED';

// const Types = {
//   REQUEST_LOGIN,
//   REQUEST_LOGIN_FAILED,
//   REQUEST_LOGIN_SUCCESS,
//   EMAIL_CHANGED,
//   PASSWORD_CHANGED,
//   REQUEST_LOGOUT,
//   REQUEST_LOGOUT_FAILED,
//   REQUEST_LOGOUT_SUCCESS,
// };

// export { Types };
