/**
 * @author: Nguyen Van Viet
 * @email: vietqb9779@gmail.com
 */
const SEARCH_REQUEST = 'SEARCH_REQUEST';
const SEARCH_REQUEST_SUCCESS = 'SEARCH_REQUEST_SUCCESS';
const SEARCH_REQUEST_FAILED = 'SEARCH_REQUEST_FAILED';
//
const NAME_CHANGED = 'NAME_CHANGED';

const Types = {
  SEARCH_REQUEST,
  SEARCH_REQUEST_FAILED,
  SEARCH_REQUEST_SUCCESS,
  NAME_CHANGED,
};
export { Types };
