export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_REQUEST_SUCCESS = "SEARCH_REQUEST_SUCCESS";
export const SEARCH_REQUEST_FAILED = "SEARCH_REQUEST_FAILED";
//
export const NAME_CHANGED = "NAME_CHANGED";
